version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/awsdemo.jar
  discard-paths: yes
